version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.maven.plugins:maven-surefire-plugin
    versions:
    - "> 2.22.0"
  - dependency-name: org.junit.platform:junit-platform-surefire-provider
    versions:
    - "> 1.1.0"
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-params
    versions:
    - 5.7.0
  - dependency-name: org.junit.platform:junit-platform-runner
    versions:
    - 1.7.0
  - dependency-name: org.junit.platform:junit-platform-launcher
    versions:
    - 1.7.0
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
